#version 460

layout(binding = 6) uniform atomic_uint TriCounter;

struct DrawArraysIndirectCommand
{
	uint count;
	uint instanceCount;
	uint first;
	uint baseInstance;
};

layout(std430, binding = 8) buffer BCounter
{
	DrawArraysIndirectCommand indirectCommand;
};

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main()
{
	indirectCommand.count = atomicCounter(TriCounter) * 3;
}
